# Colors (Molokai)
colors:
  # Default colors
  primary:
    background: '0x0A0E14'
    foreground: '0xeaeaea'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text:   '0x000000'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x080B10'
    red:     '0xfa2573'
    # green:   '0x98e123' # Correct Molokai colour
    green:   '0x9cff00' # Better looking colour
    yellow:  '0xdfd460'
    blue:    '0x1080d0'
    magenta: '0x8700ff'
    cyan:    '0x43a8d0'
    white:   '0xbbbbbb'

  # Bright colors
  bright:
    black:   '0x555555'
    red:     '0xf6669d'
    green:   '0xb1e05f'
    yellow:  '0xfff26d'
    blue:    '0x00afff'
    magenta: '0xaf87ff'
    cyan:    '0x51ceff'
    white:   '0xffffff'

# Window Settings
window:
  padding:
    x: 10
    y: 5
  dynamic_padding: true


font:
    # The size to use.
    size: 12
#   # The normal (roman) font face to use.
#   normal:
#     family: Ubuntu Mono derivative Powerline
#     # Style can be specified to pick a specific face.
#     style: Regular
#
#   # The bold font face
#   bold:
#     family: Ubuntu Mono derivative Powerline
#     # Style can be specified to pick a specific face.
#     style: Regular
#
#   # The italic font face
#   italic:
#     family: Ubuntu Mono derivative Powerline
#     # Style can be specified to pick a specific face.
#     style: Italic
