# Colors (Molokai)
colors:
    # Default colors
    primary:
        background: '#0A0E14'
        foreground: '#EAEAEA'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
        text:   '#000000'
        cursor: '#FFFFFF'

    # Normal colors
    normal:
        black:   '#080B10'
        red:     '#FA2573'
        # green:   '#98e123' # Correct Molokai colour
        green:   '#9CFF00' # Better looking colour
        yellow:  '#DFD460'
        blue:    '#1080D0'
        magenta: '#8700FF'
        cyan:    '#43A8D0'
        white:   '#BBBBBB'

        # Bright colors
    bright:
        black:   '#555555'
        red:     '#F6669D'
        green:   '#B1E05F'
        yellow:  '#FFF26D'
        blue:    '#00AFFF'
        magenta: '#AF87FF'
        cyan:    '#51CEFF'
        white:   '#FFFFFF'

# Window Settings
window:
    padding:
        x: 8
        y: 4
    dynamic_padding: false
    decorations: ButtonLess

# Font Settings
font:
    # The size to use.
    size: 12

    # Offset is the extra space around each character. `offset.y` can be thought of
    # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
    offset:
        x: 0
        y: 1
#   # The normal (roman) font face to use.
#   normal:
#     family: Ubuntu Mono derivative Powerline
#     # Style can be specified to pick a specific face.
#     style: Regular
#
#   # The bold font face
#   bold:
#     family: Ubuntu Mono derivative Powerline
#     # Style can be specified to pick a specific face.
#     style: Regular
#
#   # The italic font face
#   italic:
#     family: Ubuntu Mono derivative Powerline
#     # Style can be specified to pick a specific face.
#     style: Italic
