# Colors (Molokai)
colors:
    # Default colors
    primary:
        background: '#0A0E14'
        foreground: '#EAEAEA'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
        text:   '#000000'
        cursor: '#FFFFFF'

    # Normal colors
    normal:
        black:   '#080B10'
        red:     '#FA2573'
        # green:   '#98e123' # Correct Molokai colour
        green:   '#9CFF00' # Better looking colour
        yellow:  '#DFD460'
        blue:    '#1080D0'
        magenta: '#8700FF'
        cyan:    '#43A8D0'
        white:   '#BBBBBB'

        # Bright colors
    bright:
        black:   '#555555'
        red:     '#F6669D'
        green:   '#B1E05F'
        yellow:  '#FFF26D'
        blue:    '#00AFFF'
        magenta: '#AF87FF'
        cyan:    '#51CEFF'
        white:   '#FFFFFF'

# Window Settings
window:
    padding:
        x: 8
        y: 4
    dynamic_padding: false
    decorations: ButtonLess

# Font Settings
font:
  size: 15
  offset:
      x: 1
      y: 1

  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Regular

  italic:
    family: Ubuntu Mono
    style:  Italic

