#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m config debug_output on

# bar settings
yabai -m config top_padding                 0

# global settings
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         autoraise

yabai -m config window_placement            second_child
yabai -m config window_topmost              off

yabai -m config window_opacity              off
yabai -m config window_opacity_duration     0.0
yabai -m config window_shadow               off

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                off

# Mouse support
yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# general space settings
yabai -m config layout                      bsp
yabai -m config bottom_padding              0
yabai -m config left_padding                0
yabai -m config right_padding               0
yabai -m config window_gap                  0

# border settings
yabai -m config window_border               on
yabai -m config window_border_width         1
yabai -m config active_window_border_color  0xFFD5FF80
yabai -m config normal_window_border_color  0xFF242936

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add app='^JetBrains Toolbox$' manage=off
yabai -m rule --add app='^Surfshark$' manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add title='Preferences$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# send windows to spaces
yabai -m rule --add app='^Alacritty$' space=1

#> social
yabai -m rule --add app='^Slack$' space=2
yabai -m rule --add app='^Telegram$' space=2
yabai -m rule --add app='^WhatsApp$' space=2

#> internet
yabai -m rule --add app='^Chrome$' space=3
yabai -m rule --add app='^Google Chrome$' space=3
yabai -m rule --add app='^Brave$' space=3
yabai -m rule --add app='^Brave Browser$' space=3

#> code
multiple_display_setup=$(yabai -m query --displays | jq -r 'length == 2')
if [ $(yabai -m query --displays | jq -r 'length == 2') != false ]; then
	yabai -m rule --add app='^Code$' display=2
else
	yabai -m rule --add app='^Code$' space=4
fi

#> unity
yabai -m rule --add app='^Unity$' space=5
yabai -m rule --add title='^Unity$' space=5
yabai -m rule --add app='^Unity Hub$' space=5
yabai -m rule --add app='^Unity Multitool$' space=5

echo "yabai configuration loaded.."
